Event api participants
lhalam/event_manager pull request #4
Opened 2016-10-25 18:52 UTC by Scandie

Realization of API for user assignment to event.

2016-10-26 18:11 UTC, sbufan commented
+ Code looks good

2016-10-26 18:13 UTC, sbufan reviewed
Code looks good

2016-10-26 18:40 UTC, VKotsovskyi requested changes
In general looks good, but need some improvements.

2016-10-26 18:40 UTC, VKotsovskyi commented on events/event/views.py
> +        """
code says exactly what is written in a comment. No need comment in this case.

2016-10-26 18:40 UTC, VKotsovskyi commented on events/event/views.py
> +        not_existing_users, successfully_added = [], []
this works slower than one by one assignment.

2016-10-26 18:40 UTC, VKotsovskyi commented on events/event/views.py
> +        data = json.loads(request.body.decode())
to general name. Add specific names.

2016-10-26 18:40 UTC, VKotsovskyi commented on events/event/views.py
> +        for username in data.get('participants'):
This will crash if no key `participants` exists in the request.

2016-10-26 18:40 UTC, VKotsovskyi commented on events/event/views.py
> +                instance.save()
Check if you really need this.

2016-10-26 18:40 UTC, VKotsovskyi commented on events/event/views.py
> +            }, status=404)
404 not appropriate status for this. You still add at least some users.

2016-10-26 18:40 UTC, VKotsovskyi commented on events/events/urls.py
> +    url(r'^api/v1/events/', include('event.urls', namespace='event'))
I would recommend creating separate file `api_urls` where incluse all urls files from apps, and here include that file with url. Example -  
``` python 
url(r'^api/v1/', include('events.apy_urls', namespace='event'))
```

2016-10-26 20:25 UTC, Scandie commented on events/events/urls.py
> +    url(r'^api/v1/events/', include('event.urls', namespace='event'))
I think we should discuss it later and, if needed, add this changes. By now, everyone follows this structure.

2016-10-28 13:55 UTC, yevgenbehen requested changes

2016-10-28 13:55 UTC, yevgenbehen commented on events/event/models.py
> +    def get_all():
Please do not use `objects.all()` and do not create `get_all()` method

2016-10-28 13:55 UTC, yevgenbehen commented on events/event/views.py
> +            return JsonResponse({"error_message": "Not given any participants"}, status=400)
Error message in such cases should sound like "Invalid payload". No details should be provided

2016-10-28 13:55 UTC, yevgenbehen commented on events/events/settings.py
> +    # 'django.middleware.csrf.CsrfViewMiddleware',
Do not commit commented code

2016-11-01 11:02 UTC, VKotsovskyi approved these changes

2016-11-01 15:53 UTC, lhalam approved these changes

2016-11-01 16:47 UTC, merged