Companies
lhalam/event_manager pull request #8
Opened 2016-11-04 00:33 UTC by Scandie

2016-11-08 11:42 UTC, ForeverYouth commented on events/companies/forms.py
> +class CompanyForm(forms.Form):
Why you don't use ModelForm?

2016-11-10 15:47 UTC, VKotsovskyi requested changes

2016-11-10 15:47 UTC, VKotsovskyi commented on events/companies/models.py
> +        return [team.name for team in Company.get_by_id(company_id).teams.all()]
Why do you need only names?

2016-11-10 15:47 UTC, VKotsovskyi commented on events/companies/models.py
> +        company = Company.objects.filter(admin=request.user).first()
Why didn't you use `get` inside of `try-except`? Just curious your opinion:))

2016-11-10 15:47 UTC, VKotsovskyi commented on events/companies/views.py
> +            if not request.user.is_superuser:
You can unite this two `if`s into one with `and` as far as I can see.

2016-11-10 15:47 UTC, VKotsovskyi commented on events/companies/views.py
> +    def check_company_rights(request, company):
I would say this is private method. Are you going to use it in any other Classes?

2016-11-10 15:47 UTC, VKotsovskyi commented on events/companies/views.py
> +        else:
Why didn't you used `elif`?

2016-11-10 15:47 UTC, VKotsovskyi commented on events/companies/views.py
> +        if Company.get_user_company(request) != company:
Looks like there are few more places where you can use `and` instead of two `if`s

2016-11-10 19:11 UTC, Scandie commented on events/companies/models.py
> +        company = Company.objects.filter(admin=request.user).first()
@VKotsovskyi Can't really say. Would the `try-except` match better for this purpose?

2016-11-10 19:14 UTC, Scandie commented on events/companies/views.py
> +    def check_company_rights(request, company):
@VKotsovskyi By now `check_company_rights` method is used in all of the three views.

2016-11-10 19:55 UTC, VKotsovskyi commented on events/companies/views.py
> +    def check_company_rights(request, company):
+

2016-11-10 20:02 UTC, VKotsovskyi approved these changes
Good Job 👍

2016-11-11 12:23 UTC, ghost approved these changes

2016-11-11 12:24 UTC, merged