Profile
lhalam/event_manager pull request #9
Opened 2016-11-06 16:58 UTC by Roksolanka

Added profile model and view. Added view FileManager.

2016-11-07 14:06 UTC, Scandie requested changes

2016-11-07 14:06 UTC, Scandie commented on events/events/urls.py
> +    url(r'^profile/', include('profiles.urls', namespace='profiles')),
@Roksolanka please use `api/v1/profile/`

2016-11-07 14:36 UTC, Scandie commented on events/profiles/admin.py
> +admin.site.register(UserProfile)
@Roksolanka add empty line at the end of the file.

2016-11-07 19:09 UTC, yevgenbehen commented on events/profiles/models.py
> +    def get_all(cls):
No need in this method.

2016-11-07 19:09 UTC, yevgenbehen commented on events/events/urls.py
> +    url(r'^profile/', include('profiles.urls', namespace='profiles')),
+1 to @Scandie comment

2016-11-07 19:09 UTC, yevgenbehen commented on events/profiles/views.py
> +    def __get_dict(self, profile):
This method does not get dict - it gets JSON. Please rename method.

2016-11-07 19:09 UTC, yevgenbehen commented on events/profiles/views.py
> +import boto3
Why do you need boto3? I do not see it's usage in code

2016-11-07 19:09 UTC, yevgenbehen commented on requirements.txt
> +botocore==1.4.65
Where do you use this?

2016-11-07 19:09 UTC, yevgenbehen commented on requirements.txt
> +s3transfer==0.1.9
The same question here.

2016-11-07 19:09 UTC, yevgenbehen commented on events/profiles/views.py
> +        conn = S3Connection(local_settings.ACCESS_KEY_ID, settings.SECRET_KEY)
You can use private method `__connect_to_S3` here

2016-11-07 19:09 UTC, yevgenbehen commented on events/profiles/views.py
> +        return conn.generate_url(300, "GET", bucket_name, key)
@Roksolanka you have told on today's meeting that it does not work for you and you can't connect to S3 second time. Could you please be more specific? What error did you get and please provide more details about circumstances? Thank you!

2016-11-13 20:54 UTC, BorysYudin commented on events/profiles/views.py
> +                if form.is_valid():
It would be better validate data at first and then assign it to profile fields.

2016-12-28 19:56 UTC, Scandie approved these changes

2016-12-29 15:20 UTC, merged